# Generated by Django 5.1.4 on 2025-05-05 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useremails_rename_type_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsprofile',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='government_ids/'),
        ),
        migrations.AddField(
            model_name='doctorsprofile',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AddField(
            model_name='doctorsprofile',
            name='medical_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorsprofile',
            name='practice_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history_reports',
            field=models.FileField(blank=True, null=True, upload_to='medical_history_reports/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_medical_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pharmacystoreprofile',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='useremails',
            name='token_expiration',
            field=models.DateTimeField(),
        ),
    ]
